// Run: node scripts/audit.mjs   (also: npm run audit)
import fs from "fs";
import { products, CATEGORIES, matches, priceLabel, isRange, lineTotal, money } from "../src/catalogue.js";

const txt = fs.readFileSync(new URL("../docs/client-product-list.txt", import.meta.url), "utf8");
const catMap = { "Gas & Cooking": 1, "Building Materials": 1, Solar: 1, Electrical: 1, "Power Tools": 1, "PA Systems": 1, Audio: 1 };
const client = [...txt.matchAll(/^(\d\d)\. (.+?) — (.+?) \[(.+?)\]\s*$/gm)].map(m => ({ n: +m[1], name: m[2], price: m[3], cat: m[4] }));
let fail = 0; const bad = (m) => { fail++; console.log("  FAIL:", m); };

console.log(`Client list rows: ${client.length}; site products: ${products.length}`);
if (client.length !== 33 || products.length !== 33) bad("expected 33/33");
if (new Set(products.map(p => p.id)).size !== 33 || new Set(products.map(p => p.name)).size !== 33) bad("duplicate id/name");

const rows = [];
client.forEach((c, i) => {
  const p = products[i]; const issues = [];
  if (p.name !== c.name) issues.push(`name "${p.name}" != "${c.name}"`);
  if (p.category !== c.cat) issues.push(`category ${p.category} != ${c.cat}`);
  const cp = c.price.replace(/\s*\(.*\)/, "");
  const exp = cp.match(/\$([\d.]+)[–-]\$([\d.]+)/);
  if (exp) { if (!(isRange(p) && p.priceMin === +exp[1] && p.priceMax === +exp[2])) issues.push(`range mismatch (${cp})`); }
  else { const v = +cp.match(/\$([\d.]+)/)[1]; if (isRange(p) || p.price !== v) issues.push(`price ${p.price} != ${v}`); }
  if (/mtr|metre/.test(c.price) && p.unit !== "per metre") issues.push("per-metre lost");
  if (p.image && !fs.existsSync(new URL("../public" + p.image, import.meta.url))) issues.push("image file missing");
  if (p.image && !/^\/products\/[a-z]+\/[a-z0-9-]+\.webp$/.test(p.image)) issues.push("bad image path/name");
  if (!matches(p, p.name) ) issues.push("not searchable by own name");
  if (!matches(p, p.category)) issues.push("not searchable by category");
  if (p.brand && !matches(p, p.brand)) issues.push("not searchable by brand");
  issues.forEach(bad);
  rows.push({ n: c.n, name: p.name, category: p.category, price: isRange(p) ? priceLabel(p) + " " + p.unit : (p.unit === "per metre" ? "$1 per metre" : priceLabel(p)), image: p.image ? "VERIFIED PHOTO" : "IMAGE REQUIRED", status: issues.length ? "FAIL" : (p.image ? "PASS" : "PASS (data) / IMAGE REQUIRED") });
});

const search = (q) => products.filter(p => matches(p, q)).map(p => p.id).sort((a, b) => a - b);
const tests = {
  solar: [12, 13, 14, 15], grinder: [20, 21], jadever: [20, 21, 22, 24, 25],
  gas: [1, 2, 3, 4, 5, 6, 7, 8], "tile cutter": [22], chainsaw: [25], "chain saw": [25], jbl: [26, 27, 28], mixer: [30, 31],
  "345w": [12], "60a": [14], "20kg": [1], "800mm": [22], elephant: [11], polyda: [10], vision: [31], subwoofer: [32], soundbar: [33], "sound bar": [33], skimming: [9], planer: [23],
};
console.log("\nSearch tests");
for (const [q, want] of Object.entries(tests)) {
  const got = search(q); const ok = want.every(id => got.includes(id)) && (q === "gas" ? true : got.every(id => want.includes(id)));
  console.log(`  ${ok ? "ok  " : "FAIL"} "${q}" -> ${got.join(",")}`); if (!ok) bad(`search ${q}: wanted ${want} got ${got}`);
}
// 'solar' must return exactly the four solar products; 'ac' must not match "Contractors"
if (search("ac").includes(10)) bad('"ac" matched Contractors');

// Cart arithmetic
const p12 = products[11]; if (lineTotal(p12, 2) !== 100) bad("345W line total");
if (lineTotal(products[14], 1) !== null || lineTotal(products[31], 1) !== null) bad("range product got a fake fixed total");
if (lineTotal(products[7], 12) !== 12) bad("gas pipe 12 m should be $12");

console.table(rows.map(r => ({ "#": r.n, PRODUCT: r.name, CATEGORY: r.category, PRICE: r.price, IMAGE: r.image, STATUS: r.status })));
const imgs = rows.filter(r => r.image === "VERIFIED PHOTO").length;
console.log(`\n33/33 products present · prices/categories/names checked against client list · ${imgs} verified photos · ${33 - imgs} IMAGE REQUIRED placeholders · ${fail} failures`);
fs.writeFileSync(new URL("../AUDIT.md", import.meta.url),
`# Macrowan catalogue audit\n\nGenerated by \`npm run audit\` against docs/client-product-list.txt.\n\n| # | Product | Category | Price | Image | Status |\n|---|---|---|---|---|---|\n` + rows.map(r => `| ${r.n} | ${r.name} | ${r.category} | ${r.price} | ${r.image} | ${r.status} |`).join("\n") + `\n\n**Result:** 33/33 present, 33/33 name/price/category match, ${imgs} verified photos, ${33 - imgs} IMAGE REQUIRED (exact product image not verified), ${fail} failures.\n`);
process.exit(fail ? 1 : 0);
